#!/bin/bash

# Display ASCII art
echo -e "\x1b[47m                                       \x1b[0m"
echo -e "\x1b[47m                                       \x1b[0m"
echo -e "\x1b[47m                                       \x1b[0m"
echo -e "\x1b[44m                                       \x1b[0m"
echo -e "\x1b[44m           Slovakia Reborn             \x1b[0m"
echo -e "\x1b[44m                                       \x1b[0m"
echo -e "\x1b[41m                                       \x1b[0m"
echo -e "\x1b[41m                                       \x1b[0m"
echo -e "\x1b[41m                                       \x1b[0m"

# Script starts here
echo -e "\n\033[1;31m[INFO]\033[0m Terminating all running screen sessions..."
pkill -9 -f screen
pkill -9 screen
echo -e "\033[1;32m[OK]\033[0m All screen sessions terminated."

echo -e "\033[1;34m[INFO]\033[0m Cleaning up system..."
(
    sysctl -w net.ipv6.conf.all.disable_ipv6=1
    sysctl -w net.ipv6.conf.default.disable_ipv6=1
    sysctl -w net.ipv6.conf.lo.disable_ipv6=1
) >/dev/null 2>&1
echo -e "\033[1;32m[OK]\033[0m System cleanup completed."

echo -e "\033[1;36m[INFO]\033[0m Starting all screen processes..."
declare -a Screens=($(ls /root/Slovakia/scripts/ | grep -v "run"))
for i in ${Screens[*]}; do
    screen -dmS ${i} ./${i}
    echo -e "\033[1;32m[OK]\033[0m Started screen session: ${i}"
    echo -e "\033[1;33m[INFO]\033[0m To attach: screen -rx ${i}"
    echo
done
echo -e "\033[1;32m[ALL DONE]\033[0m All screen processes are running."